name: CMake Ubuntu CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          cmake --build .
          ./runit-selftest
